# Generated by Django 4.2 on 2026-05-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('aadhar_no', models.BigIntegerField()),
                ('mobile_no', models.BigIntegerField()),
                ('district', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.BigIntegerField(null=True)),
                ('occupation', models.CharField(max_length=100, null=True)),
                ('cust_id', models.CharField(max_length=100, null=True)),
                ('utype', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_type', models.CharField(max_length=100, null=True)),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('mobile_no', models.BigIntegerField()),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('upload_aadhar', models.ImageField(upload_to='documents/')),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=100, null=True)),
                ('acc_no', models.CharField(max_length=100, null=True)),
                ('cust_no', models.CharField(max_length=100, null=True)),
                ('amount', models.BigIntegerField(null=True)),
                ('interest', models.IntegerField(null=True)),
                ('issue_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('loan_status', models.CharField(max_length=100, null=True)),
                ('payment_mode', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('particular', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('deposit', models.IntegerField(blank=True, null=True)),
                ('withdraw', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('cdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=100, null=True)),
                ('customer', models.CharField(max_length=100, null=True)),
                ('acc_no', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('deposit_date', models.DateField(null=True)),
                ('particulars', models.CharField(max_length=100, null=True)),
                ('approve_status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('utype', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
